### ISSUE TITLE
【練習-親-】FlutterでWebアプリ開発入門

### ISSUE THREAD

**Issue by Shimpei-GANGAN** [Shimpei-GANGAN/flutter-practice#2]
### 内容
- [FlutterでWebアプリ開発入門](https://zenn.dev/fastriver/books/caff13da8b852c) を教材としてFlutterの練習を行う。

### TODO
- [ ] 【練習】Day1: Dartの基礎1(変数・四則演算等)
  - https://zenn.dev/fastriver/books/caff13da8b852c/viewer/cb8e8b#%E6%BC%94%E7%BF%92%E5%95%8F%E9%A1%8C
- [ ] 【練習】Day2: Day2: Dartの基礎2(関数・クラス), Hello world
  - https://zenn.dev/fastriver/books/caff13da8b852c/viewer/a15f24#%E6%BC%94%E7%BF%92 
- [ ] 【練習】Day3: Flutterの概要, Widget, State
- [ ] 【練習】Day4: レイアウト, 画面遷移(Navigator)
- [ ] 【練習】Day5: 実際にアプリ(ゲーム)を作ってみる
